version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: fake-ml-backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: fake-ml-frontend/Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
