version: "3.8"

services:
  backend:
    build:
      context: ./fake-ml-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    env_file:
      - ./fake-ml-backend/.env

  frontend:
    build:
      context: ./fake-ml-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
