name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fake-ml-backend

    steps:
      - uses: actions/checkout@v4

      # instala PNPM (opcional, puedes quitarlo si confías en la versión que traiga corepack)
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # instala Node + habilita corepack — sin cache de pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test --ci --runInBand --detectOpenHandles --forceExit
