name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fake-ml-backend # sigue valiendo para los pasos `run`

    env:
      CI: true

    steps:
      - uses: actions/checkout@v4

      # 1) pnpm primero (sigue igual)
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # tu versión
          run_install: false

      # 2) Node + caché -> añade la ruta del lockfile
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: fake-ml-backend/pnpm-lock.yaml # <-- AQUI

      - run: corepack enable

      # resto de pasos…
      - name: Cache MongoMemoryServer
        uses: actions/cache@v3
        with:
          path: ./.cache/mongodb-memory-server
          key: ${{ runner.os }}-mongo-mem-${{ hashFiles('fake-ml-backend/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Run tests
        run: pnpm test -- --ci --runInBand --detectOpenHandles --forceExit
