name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fake-ml-backend

    env:
      CI: true

    steps:
      # 1) Clona el repo
      - uses: actions/checkout@v4

      # 2) Instala pnpm **ANTES** de setup-node
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # o la versión que uses localmente
          run_install: false # no ejecuta pnpm install todavía

      # 3) Instala Node y activa la caché de dependencias de pnpm
      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 4) Activa Corepack (opcional si ya usas pnpm/action-setup)
      - run: corepack enable

      # 5) Cachea MongoMemoryServer
      - name: Cache MongoMemoryServer binary
        uses: actions/cache@v3
        with:
          path: ./.cache/mongodb-memory-server
          key: ${{ runner.os }}-mongo-mem-${{ hashFiles('pnpm-lock.yaml') }}

      # 6) Instala dependencias
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 7) Lint
      - name: Lint code
        run: pnpm lint

      # 8) Build
      - name: Build project
        run: pnpm build
